name: Build and push to Ecr

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure  Amazon Ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login To Amazon Ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Tag Docker Image
        run: |
          docker build -t react-app-ecr .
          docker tag react-app-ecr:latest 322421043052.dkr.ecr.us-east-1.amazonaws.com/ecr-test:latest
      - name: Push Docker Image to ecr
        run: docker push 322421043052.dkr.ecr.us-east-1.amazonaws.com/ecr-test:latestclea
